
VALID_LOOKUP_FILE_FORMAT = ".csv"
VALID_INPUT_FILE_FORMAT = ".txt"
VALID_OUTPUT_FILE_FORMAT = ".txt"

DSTPORT_LOOKUP_KEY = "dstport"
PROTOCOL_LOOKUP_KEY = "protocol"
TAG_LOOKUP_KEY = "tag"

VERSION_2_FIELDS_COUNT = 14
DSTPORT_FIELD_INDEX = 6
PROTOCOL_FIELD_INDEX = 7

UNTAGGED_LOOKUP_KEY = "untagged"

LOG_FILE = 'log_file.log'